### ISSUE TITLE
how to disable cuda?

### ISSUE THREAD

**Issue by gschen** [Parker-Lyu/rscup2019_classifier#1]
![image](https://user-images.githubusercontent.com/839140/60085860-a7dc3700-976c-11e9-899f-e87fd13a6ec8.png)

**Comment by Parker-Lyu** [comment]
全局搜素cuda()，删除掉所有.cuda()应该就可以；
cuda()是将数据放入GPU利用GPU计算的操作，不用cuda的话会很慢，记得调低batch_size参数；
