### ISSUE TITLE
兄得 , efficentnet 没有 densnet201 猛吗？

### ISSUE THREAD

**Issue by heartInsert** [Parker-Lyu/rscup2019_classifier#2]
兄弟我看你用的densnet201 , 所以 efficentnet 效果没有 densnet201 好？

两点建议:  
1：SWA 单模型的集成   

2:  刚出了个 RAdam , 论文上效果还不错，收敛快，可以减少你的训练时间，you  can  have  a  try.

**Comment by Parker-Lyu** [comment]
感谢指教，
1、没用efficient，是因为b0-b7版本不同，模型体积会不断变大，测试了一把densenet201效果还可以，就没有花功夫调整efficient;
2、SWA 指的某种模型集成的算法吗？
3、RAdam最近了解一下，感谢指教

**Comment by heartInsert** [comment]
efficient 我挺喜欢的，有空我也试下 densenet系列吧.
SWA是个单模型集成的算法，应该能提个0.5%左右，pytorch官方有实现，https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/

**Comment by Parker-Lyu** [comment]
@heartInsert 感谢指教，以后可以多交流

**Comment by heartInsert** [comment]
互相学习，共同成长
