### ISSUE TITLE
大佬好 ClsName2id.txt的格式是什么呢

### ISSUE THREAD

**Issue by a793719595** [Parker-Lyu/rscup2019_classifier#3]
每一行的类型是  图片： ？：class

**Comment by Parker-Lyu** [comment]
数据集附带的文件

**Comment by a793719595** [comment]
您好现在好像注册不了，您能发一行txt文件的内容吗 我好照着生成自己的txt

**Comment by Parker-Lyu** [comment]
见邮件附件




------------------ 原始邮件 ------------------
发件人: "dashenyue"<notifications@github.com>;
发送时间: 2019年10月4日(星期五) 下午4:28
收件人: "Parker-Lyu/rscup2019_classifier"<rscup2019_classifier@noreply.github.com>;
抄送: "Parker"<569955036@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Parker-Lyu/rscup2019_classifier] 大佬好 ClsName2id.txt的格式是什么呢 (#3)




您好现在好像注册不了，您能发一行txt文件的内容吗 我好照着生成自己的txt

**Comment by Parker-Lyu** [comment]
> 您好现在好像注册不了，您能发一行txt文件的内容吗 我好照着生成自己的txt

已发邮箱，祝炼丹快乐
