### ISSUE TITLE
Link to dataset

### ISSUE THREAD

**Issue by deimsdeutsch** [Parker-Lyu/rscup2019_classifier#4]
can you guys share the link to the dataset baidu or google drive

**Comment by luoqingshan** [comment]
你好！我也需要这个数据集，挺急的，能帮帮忙吗？分享一下，万分感谢！！

**Comment by Parker-Lyu** [comment]
链接：https://pan.baidu.com/s/1SyfXUhdzZHLOxNMiPSlDjg 
提取码：0gvr
该数据仅用于研究交流，不能用于商业用途；如因此引发后果，由使用者独自承担责任
